<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CareerConnect.Domain\CareerConnect.Domain.csproj" />
    <ProjectReference Include="..\CareerConnect.Shared\CareerConnect.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Applications\Mappings\" />
    <Folder Include="Features\Applications\Validators\" />
    <Folder Include="Features\Authentication\Mappings\" />
    <Folder Include="Features\Authentication\Validators\" />
    <Folder Include="Features\Candidates\DTOs\" />
    <Folder Include="Features\Candidates\Interfaces\" />
    <Folder Include="Features\Candidates\Mapping\" />
    <Folder Include="Features\Candidates\Validators\" />
    <Folder Include="Features\Candidates\Services\" />
    <Folder Include="Features\Interviews\Mappings\" />
    <Folder Include="Features\Interviews\Validators\" />
    <Folder Include="Features\Interviews\Services\" />
    <Folder Include="Features\Jobs\Mappings\" />
    <Folder Include="Features\Jobs\Validators\" />
    <Folder Include="Features\Recruiters\DTOs\" />
    <Folder Include="Features\Recruiters\Interfaces\" />
    <Folder Include="Features\Recruiters\Mappings\" />
    <Folder Include="Features\Recruiters\Validators\" />
    <Folder Include="Features\Recruiters\Services\" />
    <Folder Include="Features\Resumes\DTOs\" />
    <Folder Include="Features\Resumes\Interfaces\" />
    <Folder Include="Features\Resumes\Mappings\" />
    <Folder Include="Features\Resumes\Validators\" />
    <Folder Include="Features\Resumes\Services\" />
    <Folder Include="Features\Users\DTOs\" />
    <Folder Include="Features\Users\Mappings\" />
    <Folder Include="Features\Users\Validators\" />
    <Folder Include="Features\Users\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.19" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
